import dynamixel

dyn = dynamixel.dynamixel("/dev/ttyUSB0", 1000000)

result, table = dyn.readtable(1, 0, 49)
if result == dynamixel.DYNAMIXEL_SUCCESS:
	print " MODEL NUMBER            " + str(table[0] + (table[1] << 8))
	print " VERSION                 " + str(table[2])
	print " ID                      " + str(table[3])
	print " BAUD RATE               " + str(table[4])
	print " RETURN DELAY TIME       " + str(table[5])
	print " CW ANGLE LIMIT          " + str(table[6] + (table[7] << 8))
	print " CCW ANGLE LIMIT         " + str(table[8] + (table[9] << 8))
	print " LIMIT TEMPERATURE       " + str(table[11])
	print " LOW LIMIT VOLTAGE       " + str(table[12])
	print " HIGH LIMIT VOLTAGE      " + str(table[13])
	print " MAX TORQUE              " + str(table[14] + (table[15] << 8))
	print " RETURN LEVEL            " + str(table[16])
	print " ALARM LED               " + str(table[17])
	print " ALARM SHUTDOWN          " + str(table[18])
	print " DOWN CALIBRATION        " + str(table[20] + (table[21] << 8))
	print " UP CALIBRATION          " + str(table[22] + (table[23] << 8))
	print " TORQUE ENABLE           " + str(table[24])
	print " LED                     " + str(table[25])
	print " CW COMPLIANCE MARGIN    " + str(table[26])
	print " CCW COMPLIANCE MARGIN   " + str(table[27])
	print " CW COMPLIANCE SLOPE     " + str(table[28])
	print " CCW COMPLIANCE SLOPE    " + str(table[29])
	print " GOAL POSITION           " + str(table[30] + (table[31] << 8))
	print " GOAL SPEED              " + str(table[32] + (table[33] << 8))
	print " TORQUE LIMIT            " + str(table[34] + (table[35] << 8))
	print " PRESENT POSITION        " + str(table[36] + (table[37] << 8))
	print " PRESENT SPEED           " + str(table[38] + (table[39] << 8))
	print " PRESENT LOAD            " + str(table[40] + (table[41] << 8))
	print " PRESENT VOLTAGE         " + str(table[42])
	print " PRESENT TEMPERATURE     " + str(table[43])
	print " REGISTERED INSTRUCTION  " + str(table[44])
	print " MOVING                  " + str(table[46])
	print " LOCK                    " + str(table[47])
	print " PUNCH                   " + str(table[48] + (table[49] << 8))
